# Generated by Django 4.2.7 on 2023-11-22 16:27

import books.models
import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2023)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_last_week', models.DurationField(default=datetime.timedelta(0))),
                ('reading_last_month', models.DurationField(default=datetime.timedelta(0))),
                ('last_day_total_reading_time', models.DurationField(default=datetime.timedelta(0))),
                ('daily_reading_time', django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), default=books.models.get_empty_list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
