# Generated by Django 4.2.7 on 2023-11-22 12:04

import books.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='readingprofile',
            name='daily_reading_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), default=books.models.get_empty_list, size=None),
        ),
    ]
