# Generated by Django 4.2.7 on 2023-11-19 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
