# Generated by Django 4.2.7 on 2023-11-21 19:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_readingsession_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_last_week', models.DurationField(default=datetime.timedelta(0))),
                ('reading_last_month', models.DurationField(default=datetime.timedelta(0))),
                ('last_day_total_reading_time', models.DurationField(default=datetime.timedelta(0))),
                ('daily_reading_time', models.JSONField(default=[])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
