version: '3.8'

services:
  redis:
    image: redis
    restart: always

  api:
    restart: always
    build:
      context: .
      dockerfile: ./src/api/docker/Dockerfile
      args:
        PROJECT_DIR: ${PROJECT_DIR}
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - REDIS_LOCATION=redis://redis:6379/1
    volumes:
      - ./src:$PROJECT_DIR
      - static_volume:$PROJECT_DIR/static
      - media_volume:$PROJECT_DIR/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn api.wsgi:application -b 0.0.0.0:8000"

  nginx:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./src/api/docker/nginx/
    environment:
      - PROJECT_DIR=${PROJECT_DIR}
    container_name: api_nginx
    image: api_nginx
    volumes:
      - static_volume:$PROJECT_DIR/static
      - media_volume:$PROJECT_DIR/media
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  static_volume:
  media_volume:
