version: '3.11'

services:
#  redis:
#    image: redis
#    restart: always
#
#  celery-beats:
#    restart: always
#    env_file: .env
#    build:
#      context: .
#    command: celery -A dwr beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#
#  worker:
#    restart: always
#    env_file: .env
#    build:
#      context: .
#    command: celery -A dwr worker --loglevel=INFO

  rs_api:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn api.wsgi:application -b 0.0.0.0:8000"

  nginx:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: rs_api_nginx
    image: rs_api_nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - rs_api
    ports:
      - "80:80"

volumes:
  static_volume:
  media_volume:
